### ISSUE TITLE
Query regarding property specific page(data passing between pages)

### ISSUE THREAD

**Issue by ghost** [padmanav-bitcanny/ReactWebDemo#1]
Can you suggest me any procedure so that I can display a specific property from random 200 properties.How can I pass a specific property from main page to next page?

**Comment by padmanav-bitcanny** [comment]
You may use React-Router

Some useful links : 
https://github.com/ReactTraining/react-router
https://reacttraining.com/react-router/web/guides/philosophy

**Comment by ghost** [comment]
Yes I am using React Router by which single text can be passed smoothly.But how can I transfer a JSON object that is single property(containing all the data about specific property) to next page?

**Comment by padmanav-bitcanny** [comment]
You might want to look at the "history" api in React Router.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/history.md

**Comment by ghost** [comment]
My issue is solved by using Link state.I am now working on next page
design.Hopefully I can upload my work by tomorrow.

**Comment by ghost** [comment]
Sir, my work is almost done... How do I submit my work? I mean through
Gmail or through my git repo?

**Comment by padmanav-bitcanny** [comment]
You can mail us the github link of the completed work

**Comment by ghost** [comment]
Okay sir.
